Code Review
fatymahmed/bubble_sort pull request #2
Opened 2019-08-06 22:48 UTC by Urchmaney

2019-08-06 23:44 UTC, bellom commented
currently reviewing this PR

2019-08-06 23:56 UTC, bellom requested changes
Hi @Urchmaney @fatymahmed,
Nice work using the `GitHub Flow`, kindly be aware that you are to use `Git Flow` in the next project.
Short Explanation Hint: 
`GitHub Flow`: Pull Requests is raise from feature branches to the master.
`Git Flow`: Pull Requests is raise from feature branches to the development.
I tested the `bubble_sort_by` method, it gave wrong output at my end....
output > 0..3
expected output > ["hi","hey", "hello"]

Kindly fix the mentioned issues, fix linter and re-submit for review.

2019-08-07 00:07 UTC, bellom requested changes

2019-08-07 00:07 UTC, bellom commented on bubble_sort.rb
> +      arr[index+1] = tmp
Kindly know that one the Microverse guidelines encourage students to leave space around operators [read more](https://github.com/github/rubocop-github/blob/master/STYLEGUIDE.md#ruby-style-guide)
And you can see the linter also caught that......kindly fix it.

2019-08-07 00:07 UTC, bellom commented on bubble_sort.rb
> +    check=yield(array[j],array[j + 1])
Kindly know that one the Microverse guidelines encourage students to leave space around operators [read more](https://github.com/github/rubocop-github/blob/master/STYLEGUIDE.md#ruby-style-guide)
And you can see the linter also caught that......kindly fix it.

2019-08-07 00:07 UTC, bellom commented on bubble_sort.rb
> +    array[j]=array[j + 1]
Kindly know that one the Microverse guidelines encourage students to leave space around operators [read more](https://github.com/github/rubocop-github/blob/master/STYLEGUIDE.md#ruby-style-guide)
And you can see the linter also caught that......kindly fix it.

2019-08-07 20:57 UTC, mosaaleb requested changes
#### Well done@fatymahmed @Urchmaney 

The logic is right and the test cases have passed :clap:. But you still have a lot of problems in your code as mentioned by my fellow TSE related to styling guidelines.

![Screenshot from 2019-08-07 22-40-45](https://user-images.githubusercontent.com/4246637/62657246-5677b800-b966-11e9-9831-d47216ff102c.png)

- [ ] I see that you have `.rubocop.yml` in your repo. Please fix all related problems indicated by rubocop plugin.

- [ ] Please, see my comments below.

Kindly handle these issues and submit a new code review.

### Happy Coding :computer:

2019-08-07 20:57 UTC, mosaaleb commented on bubble_sort.rb
> +
Please remove those curly braces.

2019-08-07 20:57 UTC, mosaaleb commented on bubble_sort.rb
> +    temp = array[j]
You can put lines 18 and 19 in the same line, without the need for extra variable `if yield(array[j], array[j + 1]) > 0`

2019-08-08 05:07 UTC, bellom commented
## Currently reviewing this PR

2019-08-08 05:11 UTC, bellom approved these changes
Hi @Urchmaney @fatymahmed,
Nice work using the `GitHub Flow`, kindly be aware that you are to use `Git Flow` in the next project.
Good job fixing all the necessary errors from the previous reviews.
## Congratulation Guys :+1:

2019-08-08 14:17 UTC, merged